"""add_vietnamese_translation_fields

Revision ID: e4daa3b6dedc
Revises: f0390667ecf9
Create Date: 2026-06-21 18:31:35.665295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4daa3b6dedc'
down_revision = 'f0390667ecf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('summary_vi', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('abstract_vi', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'abstract_vi')
    op.drop_column('papers', 'summary_vi')
    # ### end Alembic commands ###
