"""add_upvotes_to_papers

Revision ID: c692d571cab7
Revises: e4daa3b6dedc
Create Date: 2026-06-21 20:49:34.826129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c692d571cab7'
down_revision = 'e4daa3b6dedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('upvotes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'upvotes')
    # ### end Alembic commands ###
